routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Empleados\EmpleadosController;
use App\Http\Controllers\Historicos\HistoricosController;
use App\Http\Controllers\IngresoEmpleado\IngresoEmpleadosController;
use App\Http\Controllers\PDF\PDFController;
use App\Http\Controllers\ReporteIngresosDiarios\ReporteIngresosDiariosController;
use App\Http\Controllers\ReportexEmpleado\ReportexEmpleadoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('Empleado','Empleados\EmpleadosController');
Route::resource('IngresoEmpleado','IngresoEmpleados\IngresoEmpleadosController');
Route::resource('Historico','Historico\HistoricoController'); //esta es la ruta nueva
Route::get('pdfempleados','PDF\PDFController@PDF')->name('DESCARGARPDF');
Route::get('pdfingresosempleados','PDF\PDFController@PDFIngresos')->name('DESCARGARPDFINGRESOS');
Route::resource('ReporteIngresosxEmpleado','ReportexEmpleado\ReportexEmpleadoController');
Route::resource('ReporteIngresosDiarios','ReporteIngresosDiarios\ReporteIngresosDiariosController');
//definicion de rutas laravel 8
// Route::get('/home', [HomeController::class, 'index'])->name('home');
// //Route::get('/user', [UserController::class, 'index']);
// Route::resource('/Empleado', [Empleados\EmpleadosController::class, 'index']);
// Route::resource('/IngresoEmpleado', [IngresoEmpleados\IngresoEmpleadosController::class, 'index']);
// //reportes
// Route::get('pdfempleados',[PDF\PDFController::class,"PDF"])->name('DESCARGARPDF');
// Route::get('pdfingresosempleados',[PDF\PDFController::class,'PDFIngresos'])->name('DESCARGARPDFINGRESOS');
// Route::resource('ReporteIngresosxEmpleado',[ReportexEmpleado\ReportexEmpleadoController::class,'index']);
// Route::resource('ReporteIngresosDiarios',[ReporteIngresosDiarios\ReporteIngresosDiariosController::class,'index']);

resources/views/Buscadordeimagen/create.blade.php
@extends('layouts.templates')
@section('title', 'Registrar su Ingreso y/o Retiro')
@section('styles')
  <link rel="stylesheet" href="{{ asset('assets/css/toastr.min.css') }}">
@endsection
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Control de Asistencia
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="">Registro de Ingreso</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nuevo</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                 <form action="" method="POST" name="IngresoEmpleado"> 
                   @csrf 
                   @include('buscadordeimagen.form')

                   
	                     <div class="form-group mr-2">
                          
							         </div>
				          </form>
                  <input type="text" id="paraula">
                    <div id="contenidor"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        @endsection
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
<script src="{{ asset('assets/js/alerts.js')}}"></script>
<script src="{{ asset('assets/js/avgrund.js')}}"></script>
<scrip src="{{ asset('assets/js/toastr.min.js')}}"></script>

<script>

const array_imatges = [
  "flor.jpg",
  "manta.jpg",
  "fleca.jpg",
  "ment.webp",
  "feli.jpg",
  "menta.jpg",
  "fletxa.jpg",
];

window.onload = function () {
    // Input donde se introduce el texto a buscar
    let palabra = document.getElementById("parula");
    // Ejecutar con evento input
    palabra.addEventListener("input", registrar);
}

function registrar(){
    let cont = document.getElementById('contenidor');
    // Limpiar contenedor
    cont.innerHTML = '';
    
    let texto = document.getElementById("parula").value;
    // Salir si está vacío
    if(texto.trim() == '') {
        return;
    }
    // Filtrar imágenes de acuerdo al texto
    let answer = array_imatges.filter(
        // Convertir nombre y valor a minúsculas para comparar
        item => item.toLowerCase().indexOf(texto.toLowerCase()) != -1
    ); 
    // Recorrer resultados
    answer.forEach(item => {
        // Crear imagen, definiendo ancho y alto
        let img = new Image(300, 200);
        img.src = "img/" + item;
        img.alt = item;
        img.style.display = 'inline-block';
        // Agregar a contenedor
        cont.appendChild(img);
    });
}

</script>


@endsection

resources/views/Buscadordeimagen/edit.blade.php
@extends('layouts.templates')
@section('title', 'Editar Cliente')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Cliente {{$empleado->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Pagina Principal</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleado</a></li>
                <li class="breadcrumb-item active" aria-current="page">Editar</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  <form action="/Empleado/{{$empleado->id}}" method="POST">    
                    @csrf
                    @method('PATCH')   
                      
                            <div class="form-group">
                              <label for="cedula"><strong>Cedula</strong></label>
                              <input type="text" value= "{{$empleado->cinumber}}" name="cedula" id="cedula" class="form-control" placeholder="Ingrese una cedula" required>
                            </div>
                            <div class="form-group">
                              <label for="nombre"><strong>Nombre</strong></label>
                              <input type="text" value= "{{$empleado->name}}" name="nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre" autofocus required>
                            </div>
                            <div class="form-group">
                              <label for="role"><strong>ROLE</strong></label>
                              <input type="text" value= "{{$empleado->role}}" name="role" id="role" class="form-control" placeholder="Ingrese una role" required>
                            </div>
                            <div class="form-group">
                              <label for="nota"><strong>Nota</strong></label>
                              <input type="text" value= "{{$empleado->note}}" name="nota" id="nota" class="form-control" placeholder="Ingrese una nota" required>
                            </div>


	                     <div class="form-group mr-2">
      								    <a href="{{ route('Empleado.index') }}" class="btn btn-light">Regresar</a>
      								    <button type="submit" class="btn btn-primary">Actualizar</button>
      							   </div>
      						  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/Buscadordeimagen/form.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
										@if (session()->has('notificacion'))
                        					<div class="alert alert-success" role="alert">Registrado</div>
                        					{{session('notificacion')}}
                    					@endif
											
										@if (session()->has('noexiste'))
                         					 <div class="alert alert-danger" role="alert">Cedula no Registrada, Verifique</div>
											  {{session('noexite')}}
                      					@endif
<div class="row">
	
		<div class="col-12 grid-margin">
			<div class="card">
				<div class="row">
				
					<div class="col-md-6">
						
						<div class="card-body">
							
								<!-- <div class="form-group"> -->
								<div class="form-group">
									<label for="empleado_id"><strong>Cedula</strong></label>
									<input type="text" name="empleado_id" id="empleado_id" class="form-control" placeholder="Ingrese numero cedula"  tabindex="0" autofocus required>
								</div>


			


								
										<form action="" method="POST" name="IngresoEmpleado">
											@csrf
											<button class="btn btn-success float-right mt-4 ml-2 " id="agregar" tabindex="1" >Registar</button> 
											{{-- <a href="javascript:window.print()" class="btn btn-inverse waves-effect waves-light"><i class="fa fa-print m-r-5"></i> Imprimir</a> --}}
										</form>	
										
								</div>
								
					</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	@section('scripts')
	
	
	@endsection
	<script>
$("body").on("keydown", "input, select, textarea", function(e) {
  var self = $(this),
    form = self.parents("form:eq(0)"),
    focusable,
    next;
  
  // si presiono el enter
  if (e.keyCode == 13) {
    // busco el siguiente elemento
    focusable = form.find("input,a,select,button,textarea").filter(":visible");
    next = focusable.eq(focusable.index(this) + 1);
    
    // si existe siguiente elemento, hago foco
    if (next.length) {
      next.focus();
    } else {
      // si no existe otro elemento, hago submit
      // esto lo podrías quitar pero creo que puede
      // ser bastante útil
      form.submit();
    }
    return false;
  }
});

'use strict';

const video = document.getElementById('video');
const canvas = document.getElementById('canvas');
const snap = document.getElementById("snap");
const errorMsgElement = document.querySelector('span#errorMsg');

const constraints = {
  audio: true,
  video: {
    width: 1280, height: 720
  }
};

// Access webcam
async function init() {
  try {
    const stream = await navigator.mediaDevices.getUserMedia(constraints);
    handleSuccess(stream);
  } catch (e) {
    errorMsgElement.innerHTML = `navigator.getUserMedia error:${e.toString()}`;
  }
}

// Success
function handleSuccess(stream) {
  window.stream = stream;
  video.srcObject = stream;
}

// Load init
init();

// Draw image
var context = canvas.getContext('2d');
snap.addEventListener("click", function() {
        context.drawImage(video, 0, 0, 640, 480);
});



</script>

resources/views/Buscadordeimagen/index.blade.php
@extends('layouts.templates')
@section('title', 'Listado de ingresos')
@section('styles')
  <style type="text/css">
    .unstyled-button{
      border: none;
      padding: 0;
      background: none;
    }
  </style>
@endsection
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            Lista de Ingresos
            </h3>
            
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ingresos</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>Empleados</h3>
                </div>
                <div>
                  {{-- <a href="{{route('DESCARGARPDFINGRESOS')}}" class="btn btn-success"> --}}
                    <i class="fas fa-download"></i>
                  </a>
                   {{-- <a href="" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a > --}}
                </div>
              </div><br>

              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>ID</th>
                            <th>CEDULA</th>
                            <th>FOTO</th>
                            <th>INGRESO</th>
                            <th>SALIDA</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        <!-- @foreach ($marcaingresos as $ingreso)
                        	<tr>
                            <td scope="row">{{ $ingreso->id }}</td>
                            {{-- <td>
                               <a href="{{ route('IngresoEmpleado.show', $ingreso) }}">{{ $ingreso->cinumber }}</a> 
                              
                            </td> --}}
                            <td>{{ $ingreso->cinumber }}</td>
                            <td>{{ $ingreso->photourl }}</td>
                            <td>{{ $ingreso->created_at }}</td>
                            <td>{{ $ingreso->updated_at }}</td>
                            {{-- <td>{{ $empleado->note }}</td> --}}
                            <td>
                            <form action="{{route('IngresoEmpleado.destroy',$ingreso->id)}}" method="POST">    <a href="{{ route('IngresoEmpleado.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                            @method('DELETE')
                                            @csrf 
                              <a href="{{ route('IngresoEmpleado.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                                   <i class="far fa-edit"></i>
                                 </a>
                                 <button title="Eliminar" class="jsgrid-button jsgrid-delete-button unstyled-button">
                                   <i class="far fa-trash-alt" type="submit"></i>
                                 </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                         -->
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
 @endsection
@section('scripts')
	<script src="{{asset ('assets/js/data-table.js')}}"></script>
@endsection 

resources/views/Buscadordeimagen/show.blade.php
@extends('layouts.template')
@section('title', 'Categoría')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Categoría {{$category->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorías</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  	
	                     <div class="form-group">
			                  <label for="name"><strong>Nombre</strong></label>
			                  <input type="text" value="{{$category->name}}" name="name" id="name" class="form-control" disabled>
			                </div>
			                <div class="form-group">
			                  <label for="description"><strong>Descripción</strong></label>
			                  <input type="text" name="description" value="{{$category->description}}" id="description" class="form-control" disabled>
			                </div>
	                     <div class="form-group mr-2">
      								    <a href="{{ route('categories.index') }}" class="btn btn-light">Regresar</a>
      							
      							   </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/Buscadordeimagen/vistareporte.blade.php
@extends('layouts.templates')
@section('title', 'Generar Reporte')
@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<div class="page-header">
            <h3 class="page-title">
              Informe de Asistencias - Personal-Laboratorio Clinico BILOBA
              
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Pagina Principal</a></li>
                <li class="breadcrumb-item"><a href="">Articulos</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li>
              </ol>
            </nav>
          </div>
<form action="{{route('ReporteIngresosxEmpleado.store')}}" method="POST">
@csrf
<div class="row">
    <div class="col-sm-8">
        <div class="row">    
            <div class="card-body">
            <label for="codigo"><strong>Vendedor</strong></label>
				            <select class="form-control" name="empleado_id" id="empleado_id" required>
				                @foreach ($empleados as $empleado)
				                <option value="{{$empleado->cinumber}}">{{$empleado->name}}</option>
								@endforeach
				            </select>                     
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Inicio</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_ini')}}" name="fecha_ini" id="fecha_ini" required>      
            </div>
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Fin</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_fin')}}" name="fecha_fin" id="fecha_fin" required> 
            </div>  
            <div class="col-sm-3">
                <button type="submit" class="btn btn-primary">Consultar</button>
            </div>                      
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
<script src="{{ asset('assets/js/alerts.js')}}"></script>
<script src="{{ asset('assets/js/avgrund.js')}}"></script>
<script src="{{ asset('assets/js/toastr.min.js')}}"></script>


		<script type="text/javascript">
		$(document).ready(function() {
			$('#empleado_id').select2();
		});
	</script>
	
@endsection
<script>
$("body").on("keydown", "input, select, textarea", function(e) {
  var self = $(this),
    form = self.parents("form:eq(0)"),
    focusable,
    next;
  
  // si presiono el enter
  if (e.keyCode == 13) {
    // busco el siguiente elemento
    focusable = form.find("input,a,select,button,textarea").filter(":visible");
    next = focusable.eq(focusable.index(this) + 1);
    
    // si existe siguiente elemento, hago foco
    if (next.length) {
      next.focus();
    } else {
      // si no existe otro elemento, hago submit
      // esto lo podrías quitar pero creo que puede
      // ser bastante útil
      form.submit();
    }
    return false;
  }
});
</script>

resources/views/Buscadordeimagen/vistareportediarios.blade.php
@extends('layouts.templates')
@section('title', 'Generar Reporte')
@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<div class="page-header">
            <h3 class="page-title">
            Informe de Asistencias - Personal-Laboratorio Clinico BILOBA
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Pagina Principal</a></li>
                <li class="breadcrumb-item"><a href="">Articulos</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li>
              </ol>
            </nav>
          </div>
<form action="{{route('ReporteIngresosDiarios.store')}}" method="POST">
@csrf
<div class="row">
    <div class="col-sm-8">
        <div class="row">    
             <div class="card-body">
            {{-- <label for="codigo"><strong>Vendedor</strong></label>
				            <select class="form-control" name="empleado_id" id="empleado_id" required>
				                @foreach ($empleados as $empleado)
				                <option value="{{$empleado->cinumber}}">{{$empleado->name}}</option>
								@endforeach
				            </select> --}}
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Inicio</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_ini')}}" name="fecha_ini" id="fecha_ini" required>      
            </div>
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Fin</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_fin')}}" name="fecha_fin" id="fecha_fin" required> 
            </div>  
            <div class="col-sm-3">
                <button type="submit" class="btn btn-primary">Consultar</button>
            </div>                      
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
<script src="{{ asset('assets/js/alerts.js')}}"></script>
<script src="{{ asset('assets/js/avgrund.js')}}"></script>
<script src="{{ asset('assets/js/toastr.min.js')}}"></script>

@endsection
<script>
$("body").on("keydown", "input, select, textarea", function(e) {
  var self = $(this),
    form = self.parents("form:eq(0)"),
    focusable,
    next;
  
  // si presiono el enter
  if (e.keyCode == 13) {
    // busco el siguiente elemento
    focusable = form.find("input,a,select,button,textarea").filter(":visible");
    next = focusable.eq(focusable.index(this) + 1);
    
    // si existe siguiente elemento, hago foco
    if (next.length) {
      next.focus();
    } else {
      // si no existe otro elemento, hago submit
      // esto lo podrías quitar pero creo que puede
      // ser bastante útil
      form.submit();
    }
    return false;
  }
});
</script>