routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Empleados\EmpleadosController;
use App\Http\Controllers\Historicos\HistoricosController;
use App\Http\Controllers\IngresoEmpleado\IngresoEmpleadosController;
use App\Http\Controllers\PDF\PDFController;
use App\Http\Controllers\ReporteIngresosDiarios\ReporteIngresosDiariosController;
use App\Http\Controllers\ReportexEmpleado\ReportexEmpleadoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('Empleado','Empleados\EmpleadosController');
Route::resource('IngresoEmpleado','IngresoEmpleados\IngresoEmpleadosController');
Route::resource('Historico','Historico\HistoricoController'); //esta es la ruta nueva
Route::get('pdfempleados','PDF\PDFController@PDF')->name('DESCARGARPDF');
Route::get('pdfingresosempleados','PDF\PDFController@PDFIngresos')->name('DESCARGARPDFINGRESOS');
Route::resource('ReporteIngresosxEmpleado','ReportexEmpleado\ReportexEmpleadoController');
Route::resource('ReporteIngresosDiarios','ReporteIngresosDiarios\ReporteIngresosDiariosController');
//definicion de rutas laravel 8
// Route::get('/home', [HomeController::class, 'index'])->name('home');
// //Route::get('/user', [UserController::class, 'index']);
// Route::resource('/Empleado', [Empleados\EmpleadosController::class, 'index']);
// Route::resource('/IngresoEmpleado', [IngresoEmpleados\IngresoEmpleadosController::class, 'index']);
// //reportes
// Route::get('pdfempleados',[PDF\PDFController::class,"PDF"])->name('DESCARGARPDF');
// Route::get('pdfingresosempleados',[PDF\PDFController::class,'PDFIngresos'])->name('DESCARGARPDFINGRESOS');
// Route::resource('ReporteIngresosxEmpleado',[ReportexEmpleado\ReportexEmpleadoController::class,'index']);
// Route::resource('ReporteIngresosDiarios',[ReporteIngresosDiarios\ReporteIngresosDiariosController::class,'index']);

app/Http/Controllers/Empleados/EmpleadosController.php
<?php

namespace App\Http\Controllers\Empleados;

use App\Http\Requests\Purchase\StoreRequest;
use App\Http\Requests\Purchase\UpdateRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\EmployeeRequest;
use Illuminate\Support\Facades\DB;
//use GuzzleHttp\Client;
use Http;
use App\employee;

class EmpleadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        set_time_limit(300);
        $empleados = employee::get();
        return view('Empleados.index', compact('empleados'));  
        //return $empleados;
    
            // $empleados = Http::get('https://newsdata.io/api/1/news?apikey=pub_798210afba7ae750836122bdb42e43b0a1a8');
            // $mostrarempleados   =   $empleados->json();
            // return view('empleados.index', compact('mostrarempleados'));
            //return $mostrarempleados;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Empleados.create');    
      }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {

        $cedula=$request->cedula;
        if (employee::where('cinumber', $cedula)->exists()) {
            return back()->with('duplicado', '');
        }
        employee::create([
            // 'CODIGO'=>Request('codigo'),
                'cinumber'=>Request('cedula'), 
                'name'=>Request('nombre'),
                'role' =>Request('role'),
                'note' =>Request('note'),
                'status' =>Request('status'),
             
         ]);
         return redirect('/Empleado');    
        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empleado=employee::findOrFail($id);
        //$articulos=Articulo::all();
         return view('Empleados.edit')->with('empleado',$empleado);   
         }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $empleado=employee::findOrFail($id);
        $empleado->cinumber=$request->input('cedula');
        $empleado->name=$request->input('nombre');
        $empleado->role=$request->input('role');
        $empleado->note=$request->input('nota');
        $empleado->status=$request->input('status');
        $empleado->fill($request->all());
        $empleado->save();
          return redirect('/Empleado');    

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $empleado=employee::find($id);
        $empleado->delete();
        return redirect()->route('Empleado.index');    }
}

resources/views/empleados/create.blade.php
 @extends('layouts.templates')
@section('title', 'Registrar Cliente')
@section('content') 
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Crear Empleado
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleados</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nuevo</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                    
                 <form action="{{ route('Empleado.store') }}" method="POST" name="empleados"> 
                    @csrf 
                        @include('Empleados.form')
	                     <div class="form-group mr-2">
                          <a href="/Empleado" class="btn btn-light">Regresar</a>
                          <button type="submit" class="btn btn-primary">Guardar</button>
							        </div>
				         </form>
                  	
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection 

resources/views/empleados/edit.blade.php
@extends('layouts.templates')
@section('title', 'Editar Cliente')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Cliente {{$empleado->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleado</a></li>
                <li class="breadcrumb-item active" aria-current="page">Editar</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  <form action="/Empleado/{{$empleado->id}}" method="POST">    
                    @csrf
                    @method('PATCH')   
                      
                            <div class="form-group">
                              <label for="cedula"><strong>Cedula</strong></label>
                              <input type="text" value= "{{$empleado->cinumber}}" name="cedula" id="cedula" class="form-control" placeholder="Ingrese una cedula" required>
                            </div>
                            <div class="form-group">
                              <label for="nombre"><strong>Nombre</strong></label>
                              <input type="text" value= "{{$empleado->name}}" name="nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre" autofocus required>
                            </div>
                            <div class="form-group">
                              <label for="role"><strong>ROLE</strong></label>
                              <input type="text" value= "{{$empleado->role}}" name="role" id="role" class="form-control" placeholder="Ingrese una role" required>
                            </div>
                            <div class="form-group">
                              <label for="nota"><strong>Nota</strong></label>
                              <input type="text" value= "{{$empleado->note}}" name="nota" id="nota" class="form-control" placeholder="Ingrese una nota" required>
                            </div>
                            <div class="form-group">
                              <label><strong>Status</strong></label>
                              <select id="status" name="status" class="form-control text-center">
                              <option value="Elegir">-- Selecione --</option>
                              <option value="ACTIVO">ACTIVO</option>
                              <option value="VACACIONES">VACACIONES</option>
                              <option value="REPOSO">REPOSO</option>
                              </select>
	                          </div>


	                     <div class="form-group mr-2">
      								    <a href="{{ route('Empleado.index') }}" class="btn btn-light">Regresar</a>
      								    <button type="submit" class="btn btn-primary">Actualizar</button>
      							   </div>
      						  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/empleados/form.blade.php
			@if($errors->any())
			@endif
					@if (session()->has('duplicado'))
                      <div class="alert alert-warning" role="alert">Empleado ya se encuentra Registrado</div>
                      {{session('duplicado')}}
					@endif   

@if ($errors->has('cedula'))
    <span class="alert alert-warning">
    <span>{{$errors->first('cedula')}}</span>
    </span>
@endif
<div class="form-group">
	<label for="cedula"><strong>Cedula</strong></label>
	<input type="text" name="cedula" id="cedula" class="form-control" placeholder="Ingrese una cedula">
</div>
@if ($errors->has('nombre'))
    <span class="alert alert-warning">
    <span>{{$errors->first('nombre')}}</span>
    </span>
@endif
<div class="form-group">
	<label for="nombre"><strong>Nombre</strong></label>
	<input type="text" name="nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre" autofocus >
</div>
@if ($errors->has('role'))
    <span class="alert alert-warning">
    <span>{{$errors->first('role')}}</span>
    </span>
@endif
<div class="form-group">
	<label for="role"><strong>ROLE</strong></label>
	<input type="text" name="role" id="role" class="form-control" placeholder="Ingrese una role" >
</div>
@if ($errors->has('nota'))
    <span class="alert alert-warning">
    <span>{{$errors->first('nota')}}</span>
    </span>
@endif
<div class="form-group">
	<label for="nota"><strong>Nota</strong></label>
	<input type="text" name="nota" id="nota" class="form-control" placeholder="Ingrese una nota" >
</div>
<div class="form-group">
		<label><strong>Status</strong></label>
		<select id="status" name="status" class="form-control text-center">
		<option value="Elegir">-- Selecione --</option>
		<option value="ACTIVO">ACTIVO</option>
		<option value="VACACIONES">VACACIONES</option>
		<option value="REPOSO">REPOSO</option>
		</select>
	</div>

resources/views/empleados/index.blade.php
@extends('layouts.templates')
@section('title', 'Lista de Empleados')
@section('styles')
  <style type="text/css">
    .unstyled-button{
      border: none;
      padding: 0;
      background: none;
    }
  </style>
@endsection
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            <img class ="img-fondo2" aling="left" src="{{asset('images/biloba.jpg')}}" width="10%" />
            Listado de Empleados 
            </h3>
            
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Empleado</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>Empleados</h3>
                </div>
                <div>
                  <a href="javascript:window.print()" class="btn btn-success">
                    <i class="fas fa-download"></i>
                  </a>
                   <a href="{{ route('Empleado.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a > 
                </div>
              </div><br>

              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>ID</th>
                            <th>CEDULA</th>
                            <th>NOMBRE</th>
                            <th>ROLE</th>
                            <th>STATUS</th>
                            
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($empleados as $empleado)
                        	<tr>
                            <td scope="row">{{ $empleado->id }}</td>
                            {{-- <td>
                               <a href="{{ route('Empleado.show', $empleado) }}">{{ $empleado->name }}</a> 
                              
                            </td> --}}
                            <td>{{ $empleado->cinumber }}</td>
                            <td>{{ $empleado->name }}</td>
                            <td>{{ $empleado->role }}</td>
                            <td>{{ $empleado->status }}</td>
                            <td>
                            <form action="{{route('Empleado.destroy',$empleado->id)}}" method="POST">    <a href="{{ route('Empleado.edit', $empleado) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                            @method('DELETE')
                                            @csrf 
                              <a href="{{ route('Empleado.edit', $empleado) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                                   <i class="far fa-edit"></i>
                                 </a>
                                 <button title="Eliminar" class="jsgrid-button jsgrid-delete-button unstyled-button">
                                   <i class="far fa-trash-alt" type="submit"></i>
                                 </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
 @endsection
@section('scripts')
	<script src="{{asset ('assets/js/data-table.js')}}"></script>
@endsection 

resources/views/empleados/show.blade.php
@extends('layouts.template')
@section('title', 'Categoría')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Categoría {{$category->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorías</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  	
	                     <div class="form-group">
			                  <label for="name"><strong>Nombre</strong></label>
			                  <input type="text" value="{{$category->name}}" name="name" id="name" class="form-control" disabled>
			                </div>
			                <div class="form-group">
			                  <label for="description"><strong>Descripción</strong></label>
			                  <input type="text" name="description" value="{{$category->description}}" id="description" class="form-control" disabled>
			                </div>
	                     <div class="form-group mr-2">
      								    <a href="{{ route('categories.index') }}" class="btn btn-light">Regresar</a>
      							
      							   </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection