routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Empleados\EmpleadosController;
use App\Http\Controllers\Historicos\HistoricosController;
use App\Http\Controllers\IngresoEmpleado\IngresoEmpleadosController;
use App\Http\Controllers\PDF\PDFController;
use App\Http\Controllers\ReporteIngresosDiarios\ReporteIngresosDiariosController;
use App\Http\Controllers\ReportexEmpleado\ReportexEmpleadoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('Empleado','Empleados\EmpleadosController');
Route::resource('IngresoEmpleado','IngresoEmpleados\IngresoEmpleadosController');
Route::resource('Historico','Historico\HistoricoController'); //esta es la ruta nueva
Route::get('pdfempleados','PDF\PDFController@PDF')->name('DESCARGARPDF');
Route::get('pdfingresosempleados','PDF\PDFController@PDFIngresos')->name('DESCARGARPDFINGRESOS');
Route::resource('ReporteIngresosxEmpleado','ReportexEmpleado\ReportexEmpleadoController');
Route::resource('ReporteIngresosDiarios','ReporteIngresosDiarios\ReporteIngresosDiariosController');
//definicion de rutas laravel 8
// Route::get('/home', [HomeController::class, 'index'])->name('home');
// //Route::get('/user', [UserController::class, 'index']);
// Route::resource('/Empleado', [Empleados\EmpleadosController::class, 'index']);
// Route::resource('/IngresoEmpleado', [IngresoEmpleados\IngresoEmpleadosController::class, 'index']);
// //reportes
// Route::get('pdfempleados',[PDF\PDFController::class,"PDF"])->name('DESCARGARPDF');
// Route::get('pdfingresosempleados',[PDF\PDFController::class,'PDFIngresos'])->name('DESCARGARPDFINGRESOS');
// Route::resource('ReporteIngresosxEmpleado',[ReportexEmpleado\ReportexEmpleadoController::class,'index']);
// Route::resource('ReporteIngresosDiarios',[ReporteIngresosDiarios\ReporteIngresosDiariosController::class,'index']);

app/IngresoEmpleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class IngresoEmpleado extends Model
{
    Protected $primaryKey = "id";
    //protected $table ='clientes';
    protected $fillable = [
        'id',
        'cinumber',
        'photourl',
  
    ];
}

app/Http/Controllers/IngresoEmpleados/IngresoEmpleadosController.php
<?php

namespace App\Http\Controllers\IngresoEmpleados;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Http\Requests\Purchase\StoreRequest;
use App\Http\Requests\Purchase\UpdateRequest;
use App\Http\Controllers\Controller;
//use Intervention\Image\ImageManager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Carbon\Carbon;
use Image;
use Intervention\Image\Exception\NotReadableException;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Timemark;
use App\employee;

class IngresoEmpleadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   

    public function index()
    {
        //probando el repo
        $empleados = employee::get();
        return view('ingresoempleados.formhistorico', compact('empleados'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //se modifico este linea 46 y 49
        $fecha=Carbon::now('America/Caracas');
        //$fecha = $fecha->format('Y-m-d 00:00:00');
        $empleados = employee::get();
        return view('ingresoempleados.create', compact('empleados','fecha'));  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
     {

    
//phpinfo();

//'/timework/uploads/'
  $baseDIR = $_SERVER['DOCUMENT_ROOT']. '/timework/uploads/'.date("m", time())."/"; //C:\laragon\www\BILOBA\public  
  $baseURL = 'http://' . $_SERVER['HTTP_HOST'].'/timework/uploads/' .date("m", time())."/"; //127.0.0.1:8000/images/01/
  
  if (!file_exists($baseDIR)) {
    mkdir($baseDIR, 0755, true);
  }


             $cedula=$request->empleado_id;
             $img    = $request->get('data_url');
             $img    = str_replace('data:image/png;base64,', '', $img);
             $img    = str_replace(' ', '+', $img);
             $decodifica = base64_decode($img,true);
             $extension  = "png";
             $filename = Str::random(10).$cedula .'.'.$extension;
             $path    = $baseDIR;
             $success = file_put_contents($baseDIR .$filename,$decodifica);
             $imageURL = $baseURL . $filename;
                            if (employee::where('cinumber', $cedula)->exists()) {
                                $seregistraempleado =   new Timemark();
                                $seregistraempleado->cinumber = $request->input('empleado_id'); //bueno
                                $seregistraempleado->photourl = ltrim($imageURL,'.');//bueno
                                //dd($seregistraempleado);
                                $seregistraempleado->save();//bueno
                                return back()->with('notification', 'Registrado');//bueno
                             }
                            
                                 return back()->with('noexiste', 'cedula no registrada, verifique');//buenoi
                            
                                            
                           
         
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

  
    public function show($id)
    {
      

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ingresoempleados/create.blade.php
@extends('layouts.templates')
@section('title', 'Registrar su Ingreso y/o Retiroo')
@section('styles')
  <link rel="stylesheet" href="{{ asset('assets/css/toastr.min.css') }}">
@endsection
@section('content')
////probando repo
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Control de Asistencia
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('IngresoEmpleado.index') }}">Registro de Ingreso y/o Salida</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nuevo</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}
             
              
              <div class="row">
                  <div class="col-12">
                 
                 <form action="{{ route('IngresoEmpleado.store') }}" method="POST" name="IngresoEmpleado"> 
                   @csrf 
                  @include('ingresoempleados.form') 
	                     <div class="form-group mr-2">
                          
							         </div>
				          </form>
                  	
                </div>
              </div>
            </div>
          </div>
        </div>
        @endsection
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
<script src="{{ asset('assets/js/alerts.js')}}"></script>
<script src="{{ asset('assets/js/avgrund.js')}}"></script>
<script src="{{ asset('assets/js/toastr.min.js')}}"></script>



@endsection

resources/views/ingresoempleados/edit.blade.php
@extends('layouts.templates')
@section('title', 'Editar Cliente')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Cliente {{$empleado->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Pagina Principal</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleado</a></li>
                <li class="breadcrumb-item active" aria-current="page">Editar</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  <form action="/Empleado/{{$empleado->id}}" method="POST">    
                    @csrf
                    @method('PATCH')   
                      
                            <div class="form-group">
                              <label for="cedula"><strong>Cedula</strong></label>
                              <input type="text" value= "{{$empleado->cinumber}}" name="cedula" id="cedula" class="form-control" placeholder="Ingrese una cedula" required>
                            </div>
                            <div class="form-group">
                              <label for="nombre"><strong>Nombre</strong></label>
                              <input type="text" value= "{{$empleado->name}}" name="nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre" autofocus required>
                            </div>
                            <div class="form-group">
                              <label for="role"><strong>ROLE</strong></label>
                              <input type="text" value= "{{$empleado->role}}" name="role" id="role" class="form-control" placeholder="Ingrese una role" required>
                            </div>
                            <div class="form-group">
                              <label for="nota"><strong>Nota</strong></label>
                              <input type="text" value= "{{$empleado->note}}" name="nota" id="nota" class="form-control" placeholder="Ingrese una nota" required>
                            </div>


	                     <div class="form-group mr-2">
      								    <a href="{{ route('Empleado.index') }}" class="btn btn-light">Regresar</a>
      								    <button type="submit" class="btn btn-primary">Actualizar</button>
      							   </div>
      						  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/ingresoempleados/form.blade.php
<?
// require 'vendor/autoload.php';
// use Intervention\Image\ImageManager;
?>
<!DOCTYPE html>
<html lang="es">
    <head>
<style>



</style>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Capturar Webcam con HTML5 y Javascript">
    <meta name="author" content="Raúl Prieto Fernández">
    <title>Capturar Webcam con HTML5 y Javascript</title>
    <link href="/images/style.css" rel="stylesheet" type="text/css">
    </head>
<body onload="">

<!-- Cabecera -->
<h1>Registre su ingreso, Laboratorio Clinico BILOBA</h1>


<input type="fecha" name="fecha" id="fecha" class="form-control" value="{{$fecha}}" readonly="true" aling="center">								
<!-- se moficio este archivo linea 29 -->

<!-- Mensaje de error -->
<span name="errorMsg"></span>

<!-- Cargar Frame de TV y cargar el video de la webcam -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
										@if (session()->has('notificacion'))
                        					<div class="alert alert-success" role="alert">Registrado</div>
                        					{{session('notificacion')}}
                    					@endif
									
										 @if (session()->has('noexiste'))
                         					 <div class="alert alert-danger" role="alert">Cedula no Registrada, Verifique</div>
											  {{session('noexite')}}
                      					@endif 
<form action="{{ route('IngresoEmpleado.store') }}" method="POST" file="true" name="IngresoEmpleado" enctype="multipart/form-data">
@csrf
<div class="row">
	
		<div class="col-12 grid-margin">
			<div class="card">
				<div class="row">
				
					<div class="col-md-6">
						
						<div class="card-body">
							
								<!-- <div class="form-group"> -->
								<div class="form-group">
									
									<label for="empleado_id"><strong>Cedula</strong></label>
									<input type="number" name="empleado_id" id="empleado_id" class="form-control" placeholder="Ingrese numero cedula"  tabindex="0" autofocus required>
									<input class="form-control" type= "hidden" name="data_url" id="data_url"  accept ="" class="form-control"></input>
								</div>
								
								<div id="video_wrap">
    								<div id="video_overlays">
										<!-- <img src="/images/tv.jpg"></img> -->
									</div> 
    									{{-- <video id="video_frame" playsinline autoplay></video> --}}
										<video id="video_frame" preload="true" playsinline autoplay muted></video>
										
								</div>
									<!-- Capturamos la imagen a través de la API web y lo mostramos en el canvas -->
									<div class="button_controller">
										<!-- Botón para capturar -->
										<button id="snap_frame">Capturar Imagen</button>
										<br/><br/>
										<!-- Imagen de la Webcam -->
										<canvas id="canvas_frame"></canvas>
										<input type="hidden" name="imagen" value="" id="imagen"/>
										
										
									</div>

									
										
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
										
											<button class="btn btn-success float-right mt-4 ml-2 " id="agregar" onclick="" tabindex="1" >Registar</button> 
		
</form>	
</div>
	
	@section('scripts')
	
	
	@endsection
<!-- Cargamos el Javascript -->
<script src="/webcam.js" async></script>
<script src="/teclaenter.js" ></script>


</body>
</html>

resources/views/ingresoempleados/formhistorico.blade.php
@extends('layouts.templates')
@section('title', 'HISTORICO EMPLEADOS')
@section('content') 
@foreach ($empleados as $empleado)
@endforeach
<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              HISTORICO EMPLEADOS
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleados</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nuevo</li>
              </ol>
            </nav>
          </div>
        
<form action="{{ route('IngresoEmpleado.historico') }}" method="POST" file="true" name="showEmpleado" enctype="multipart/form-data">
@csrf
<div class="row">
	
		<div class="col-12 grid-margin">
			<div class="card">
				<div class="row">
				
					<div class="col-md-6">
						
						<div class="card-body">
							
                        <div class="form-group">
                            <label for="nombre"><strong>Seleccione Empleado</strong></label>
                            <select name="empleado_id" id="empleado_id" class="form-control form-control-lg">
                                        <option>--- Seleccione uno ---</option>
                                        @foreach ($empleados as $empleado)
                                        <option value="{{ $empleado->cinumber }}">{{ $empleado->name }}</option>
                                        @endforeach
                            </select>
                        </div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
										
			<button class="btn btn-success float-right mt-4 ml-2 " id="agregar" onclick="" tabindex="1" >Ver Historico</button> 
		
</form>	
</div>
@endsection

@section('scripts')
		<script type="text/javascript">
		$(document).ready(function() {
			$('#empleado_id').select2();
		});
	</script>
    @endsection

resources/views/ingresoempleados/formoriginal.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
										@if (session()->has('notificacion'))
                        					<div class="alert alert-success" role="alert">Registrado</div>
                        					{{session('notificacion')}}
                    					@endif
											
										@if (session()->has('noexiste'))
                         					 <div class="alert alert-danger" role="alert">Cedula no Registrada, Verifique</div>
											  {{session('noexite')}}
                      					@endif
<div class="row">
	
		<div class="col-12 grid-margin">
			<div class="card">
				<div class="row">
				
					<div class="col-md-6">
						
						<div class="card-body">
							
								<!-- <div class="form-group"> -->
								<div class="form-group">
									<label for="empleado_id"><strong>Cedula</strong></label>
									<input type="number" name="empleado_id" id="empleado_id" class="form-control" placeholder="Ingrese numero cedula"  tabindex="0" autofocus required>
								</div>
								
								
										<form action="{{ route('IngresoEmpleado.store') }}" method="POST" name="IngresoEmpleado">
											@csrf
											<button class="btn btn-success float-right mt-4 ml-2 " id="agregar" tabindex="1" >Registar</button> 
											{{-- <a href="javascript:window.print()" class="btn btn-inverse waves-effect waves-light"><i class="fa fa-print m-r-5"></i> Imprimir</a> --}}
										</form>	
										
								</div>
								
					</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	@section('scripts')
	
	
	@endsection
	<script>

</script>

resources/views/ingresoempleados/index.blade.php
@extends('layouts.templates')
@section('title', 'Listado de ingresos')
@section('styles')
  <style type="text/css">
    .unstyled-button{
      border: none;
      padding: 0;
      background: none;
    }
  </style>
@endsection
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            Lista de Ingresos
            </h3>
            
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ingresos</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>Empleados</h3>
                </div>
                <div>
                  {{-- <a href="{{route('DESCARGARPDFINGRESOS')}}" class="btn btn-success"> --}}
                    <i class="fas fa-download"></i>
                  </a>
                   {{-- <a href="{{ route('IngresoEmpleado.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a > --}}
                </div>
              </div><br>

              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>ID</th>
                            <th>CEDULA</th>
                            <th>FOTO</th>
                            <th>INGRESO</th>
                            <th>SALIDA</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        <!-- @foreach ($marcaingresos as $ingreso)
                        	<tr>
                            <td scope="row">{{ $ingreso->id }}</td>
                            {{-- <td>
                               <a href="{{ route('IngresoEmpleado.show', $ingreso) }}">{{ $ingreso->cinumber }}</a> 
                              
                            </td> --}}
                            <td>{{ $ingreso->cinumber }}</td>
                            <td>{{ $ingreso->photourl }}</td>
                            <td>{{ $ingreso->created_at }}</td>
                            <td>{{ $ingreso->updated_at }}</td>
                            {{-- <td>{{ $empleado->note }}</td> --}}
                            <td>
                            <form action="{{route('IngresoEmpleado.destroy',$ingreso->id)}}" method="POST">    <a href="{{ route('IngresoEmpleado.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                            @method('DELETE')
                                            @csrf 
                              <a href="{{ route('IngresoEmpleado.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                                   <i class="far fa-edit"></i>
                                 </a>
                                 <button title="Eliminar" class="jsgrid-button jsgrid-delete-button unstyled-button">
                                   <i class="far fa-trash-alt" type="submit"></i>
                                 </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                         -->
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
 @endsection
@section('scripts')
	<script src="{{asset ('assets/js/data-table.js')}}"></script>
@endsection 

resources/views/ingresoempleados/show.blade.php
@extends('layouts.template')
@section('title', 'Categoría')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Categoría {{$category->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categorías</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  	
	                     <div class="form-group">
			                  <label for="name"><strong>Nombre</strong></label>
			                  <input type="text" value="{{$category->name}}" name="name" id="name" class="form-control" disabled>
			                </div>
			                <div class="form-group">
			                  <label for="description"><strong>Descripción</strong></label>
			                  <input type="text" name="description" value="{{$category->description}}" id="description" class="form-control" disabled>
			                </div>
	                     <div class="form-group mr-2">
      								    <a href="{{ route('categories.index') }}" class="btn btn-light">Regresar</a>
      							
      							   </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/ingresoempleados/showhistorico.blade.php
@extends('layouts.templates')
@section('title', 'Lista de Empleados')
@section('styles')
  <style type="text/css">
    .unstyled-button{
      border: none;
      padding: 0;
      background: none;
    }
  </style>
@endsection
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            Lista de Empleados
            </h3>
            
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item active" aria-current="page">Empleado</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>Empleados</h3>
                </div>
                <div>
                 {{-- <a href="{{route('DESCARGARPDF')}}" class="btn btn-success">
                    <i class="fas fa-download"></i>
                  </a>
                   <a href="{{ route('Empleado.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a > --}}
                </div>
              </div><br>

              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>ID</th>
                            <th>CEDULA</th>
                            <th>FOTO</th>
                            <th>ENTRADA/SALIDA</th>
                            
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($marcaingresos as $ingreso)
                        	<tr>
                            <td scope="row">{{ $empleado->id }}</td>
                            {{-- <td>
                               <a href="{{ route('Historicos.index', $ingreso) }}">{{ $ingreso->cinumber }}</a> 
                              
                            </td> --}}
                            <td>{{ $ingreso->cinumber }}</td>
                            <td>{{ $ingreso->photourl }}</td>
                            <td>{{ $ingreso->timestamp }}</td>
                           
                            <td>
                            <form action="{{route('Historicos.destroy',$ingreso->id)}}" method="POST">    <a href="{{ route('Historicos.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                            @method('DELETE')
                                            @csrf 
                              <a href="{{ route('Historicos.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                                   <i class="far fa-edit"></i>
                                 </a>
                                 <button title="Eliminar" class="jsgrid-button jsgrid-delete-button unstyled-button">
                                   <i class="far fa-trash-alt" type="submit"></i>
                                 </button>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
 @endsection
@section('scripts')
	<script src="{{asset ('assets/js/data-table.js')}}"></script>
@endsection 

resources/views/ingresoempleados/vistareporte.blade.php
@extends('layouts.templates')
@section('title', 'Generar Reporte')
@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
                              @if (session()->has('noexiste'))
                        					<div class="alert alert-danger" role="alert">No hay Registros disponibles para su consulta</div>
                        					{{session('noexiste')}}
                    					@endif
										
<div class="page-header">
            <h3 class="page-title">
              Informe de Asistencias - Personal-Laboratorio Clinico BILOBA
              
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item"><a href="">Reporte</a></li>
                {{-- <li class="breadcrumb-item active" aria-current="page">Crear Nueva</li> --}}
              </ol>
            </nav>
          </div>
<form action="{{route('ReporteIngresosxEmpleado.store')}}" method="POST">
@csrf
<div class="row">
    <div class="col-sm-8">
        <div class="row">    
            <div class="card-body">
            <label for="codigo"><strong>Empleado</strong></label>
				            <select class="form-control" name="empleado_id" id="empleado_id" required>
				                @foreach ($empleados as $empleado)
				                <option value="{{$empleado->cinumber}}">{{$empleado->name}}</option>
								@endforeach
				            </select>                     
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Inicio</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_ini')}}" name="fecha_ini" id="fecha_ini" required>      
            </div>
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Fin</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_fin')}}" name="fecha_fin" id="fecha_fin" required> 
            </div>  
            <div class="col-sm-3">
                <button type="submit" class="btn btn-primary">Consultar</button>
            </div>                      
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
<script src="{{ asset('assets/js/alerts.js')}}"></script>
<script src="{{ asset('assets/js/avgrund.js')}}"></script>
<script src="{{ asset('assets/js/toastr.min.js')}}"></script>


		<script type="text/javascript">
		$(document).ready(function() {
			$('#empleado_id').select2();
		});
	</script>
	
@endsection
<script>
$("body").on("keydown", "input, select, textarea", function(e) {
  var self = $(this),
    form = self.parents("form:eq(0)"),
    focusable,
    next;
  
  // si presiono el enter
  if (e.keyCode == 13) {
    // busco el siguiente elemento
    focusable = form.find("input,a,select,button,textarea").filter(":visible");
    next = focusable.eq(focusable.index(this) + 1);
    
    // si existe siguiente elemento, hago foco
    if (next.length) {
      next.focus();
    } else {
      // si no existe otro elemento, hago submit
      // esto lo podrías quitar pero creo que puede
      // ser bastante útil
      form.submit();
    }
    return false;
  }
});
</script>