routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Empleados\EmpleadosController;
use App\Http\Controllers\Historicos\HistoricosController;
use App\Http\Controllers\IngresoEmpleado\IngresoEmpleadosController;
use App\Http\Controllers\PDF\PDFController;
use App\Http\Controllers\ReporteIngresosDiarios\ReporteIngresosDiariosController;
use App\Http\Controllers\ReportexEmpleado\ReportexEmpleadoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('Empleado','Empleados\EmpleadosController');
Route::resource('IngresoEmpleado','IngresoEmpleados\IngresoEmpleadosController');
Route::resource('Historico','Historico\HistoricoController'); //esta es la ruta nueva
Route::get('pdfempleados','PDF\PDFController@PDF')->name('DESCARGARPDF');
Route::get('pdfingresosempleados','PDF\PDFController@PDFIngresos')->name('DESCARGARPDFINGRESOS');
Route::resource('ReporteIngresosxEmpleado','ReportexEmpleado\ReportexEmpleadoController');
Route::resource('ReporteIngresosDiarios','ReporteIngresosDiarios\ReporteIngresosDiariosController');
//definicion de rutas laravel 8
// Route::get('/home', [HomeController::class, 'index'])->name('home');
// //Route::get('/user', [UserController::class, 'index']);
// Route::resource('/Empleado', [Empleados\EmpleadosController::class, 'index']);
// Route::resource('/IngresoEmpleado', [IngresoEmpleados\IngresoEmpleadosController::class, 'index']);
// //reportes
// Route::get('pdfempleados',[PDF\PDFController::class,"PDF"])->name('DESCARGARPDF');
// Route::get('pdfingresosempleados',[PDF\PDFController::class,'PDFIngresos'])->name('DESCARGARPDFINGRESOS');
// Route::resource('ReporteIngresosxEmpleado',[ReportexEmpleado\ReportexEmpleadoController::class,'index']);
// Route::resource('ReporteIngresosDiarios',[ReporteIngresosDiarios\ReporteIngresosDiariosController::class,'index']);

app/Http/Controllers/Historico/HistoricoController.php
<?php

namespace App\Http\Controllers\Historico;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Http\Requests\HistoricoRequest;
use Carbon\Carbon;
use App\employee;
use App\Timemark;
class HistoricoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        set_time_limit(300);
        $empleados = employee::get();
        return view('historico.create', compact('empleados'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        set_time_limit(300);
        $empleados=employee::all();
        $cedula = $request->empleado_id;
        $fi = $request->fecha_ini.' 00:00:00';
        $ff = $request->fecha_fin.' 23:59:59';
    
        //$compras = DB::table('compras')->orderBy('FECHA', 'asc')->where('PROVEEDOR_ID', [$id])->get();
        //$compras = DB::table('compras')->orderBy('FECHA', 'asc')->whereBetween('FECHA', [$fi, $ff])->get();
            $ingresos = DB::table('timemark')->orderBy('timestamp', 'asc')->where('cinumber', [$cedula])->get()->whereBetween('timestamp', [$fi, $ff]);
           if ($ingresos->count())
            {
                return view ('historico.index', compact('ingresos'));
                
            }else{
                return back()->with('noexiste', '');
            }
            }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ingreso=Timemark::findOrFail($id);
        return view('historico.show')->with('ingreso',$ingreso);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ingreso=Timemark::findOrFail($id);
        //$articulos=Articulo::all();
         return view('historico.edit')->with('ingreso',$ingreso);      }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HistoricoRequest $request, $id)
    {
           
        $fi = date('Y-m-d 00:00:00');
        $ff = date('Y-m-d 23:59:59');
        $hora=Timemark::findOrFail($id);
        $hora->timestamp=$request->input('hora');
        $hora->save();
            if($hora){
                return redirect('/Historico/'.$id)->with('actualizada','');
            }
            return redirect('/Historico/'.$id)->with('invalid','');
        }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ingreso=Timemark::find($id);
        $ingreso->delete();
        return redirect()->route('historico.index'); 
    }
}

resources/views/historico/create.blade.php
 @extends('layouts.templates')
@section('title', 'Historico')
@section('content') 
@section('styles')
  <link rel="stylesheet" href="{{ asset('assets/css/toastr.min.css') }}">
@endsection
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            <img class ="img-fondo2" aling="left" src="{{asset('images/biloba.jpg')}}" width="10%" />
              Consultar Historico por Empleado
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleados</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear Nuevo</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                 <form action="{{ route('Historico.store') }}" method="POST" name="empleados"> 
                    @csrf 
                        @include('historico.form')
	                     <div class="form-group mr-2">
                          <a href="/Historico" class="btn btn-light">Regresar</a>
                          <button type="submit" class="btn btn-primary">Consultar</button>
							        </div>
				         </form>
                  	
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection 
@section('scripts')
<script src="{{ asset('assets/js/select2.js')}}"></script>
@endsection

resources/views/historico/edit.blade.php
@extends('layouts.templates')
@section('title', 'Editar Cliente')
@section('content')
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Editar Cliente {{$empleado->name}}
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Empleado.index') }}">Empleado</a></li>
                <li class="breadcrumb-item active" aria-current="page">Editar</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  <form action="/Empleado/{{$empleado->id}}" method="POST">    
                    @csrf
                    @method('PATCH')   
                      
                            <div class="form-group">
                              <label for="cedula"><strong>Cedula</strong></label>
                              <input type="text" value= "{{$empleado->cinumber}}" name="cedula" id="cedula" class="form-control" placeholder="Ingrese una cedula" required>
                            </div>
                            <div class="form-group">
                              <label for="nombre"><strong>Nombre</strong></label>
                              <input type="text" value= "{{$empleado->name}}" name="nombre" id="nombre" class="form-control" placeholder="Ingrese el nombre" autofocus required>
                            </div>
                            <div class="form-group">
                              <label for="role"><strong>ROLE</strong></label>
                              <input type="text" value= "{{$empleado->role}}" name="role" id="role" class="form-control" placeholder="Ingrese una role" required>
                            </div>
                            <div class="form-group">
                              <label for="nota"><strong>Nota</strong></label>
                              <input type="text" value= "{{$empleado->note}}" name="nota" id="nota" class="form-control" placeholder="Ingrese una nota" required>
                            </div>


	                     <div class="form-group mr-2">
      								    <a href="{{ route('Empleado.index') }}" class="btn btn-light">Regresar</a>
      								    <button type="submit" class="btn btn-primary">Actualizar</button>
      							   </div>
      						  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/historico/form.blade.php
                                       @if (session()->has('noexiste'))
                        					<div class="alert alert-danger" role="alert">No hay registros disponibles para su consulta</div>
                        					{{session('noexiste')}}
                    					@endif                                     
<div class="form-group">
<label for="nombre"><strong>Empleado</strong></label>
	<select name="empleado_id" id="empleado_id" class="form-control form-control-lg">
                <option>--- Seleccione uno ---</option>
                @foreach ($empleados as $empleado)
    	        <option value="{{ $empleado->cinumber }}">{{ $empleado->name }}</option>
                @endforeach
    </select>
</div>
<div class="col-sm-5">
            <label for="codigo"><strong>Fecha Inicio</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_ini')}}" name="fecha_ini" id="fecha_ini" required>      
            </div>
            <div class="col-sm-5">
            <label for="codigo"><strong>Fecha Fin</strong></label>
                <input class="form-control" type="date" value="{{old('fecha_fin')}}" name="fecha_fin" id="fecha_fin" required> 
</div>

@section('scripts')
		<script type="text/javascript">
		$(document).ready(function() {
			$('#empleado_id').select2();
		});
	</script>
	@endsection

resources/views/historico/index.blade.php
@extends('layouts.templates')
@section('title', 'HIstorico')
@section('styles')
  <style type="text/css">
    .unstyled-button{
      border: none;
      padding: 0;
      background: none;
    }
  </style>
@endsection
@section('content')


	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            <img class ="img-fondo2" aling="left" src="{{asset('images/biloba.jpg')}}" width="10%" />
            Historico por Empleado 
            </h3>
            
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Inicio</a></li>
                
                <li class="breadcrumb-item active" aria-current="page">Historico</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div>
                  <h3>Empleado</h3>
                </div>
                <div>
                  <a href="javascript:window.print()" class="btn btn-success">
                    <i class="fas fa-download"></i>
                  </a>
                   {{-- <a href="{{ route('Empleado.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i></a > --}}
                </div>
              </div><br>

              <div class="row">
                <div class="col-12">
                  <div class="table-responsive">
                    <table id="order-listing" class="table">
                      <thead>
                        <tr>
                            <th>ID</th>
                            <th>CEDULA</th>
                            <th>HORA</th>
                            <th>FOTO</th>
                            
                            {{-- <th>Acciones</th> --}}
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($ingresos as $ingreso)
                        	<tr>
                            <td scope="row">{{ $ingreso->id }}</td>
                            <td>{{ $ingreso->cinumber }}</td>
                            <!-- <td>{{ $ingreso->photourl }}</td> -->
                            <td>{{ $ingreso->timestamp }}</td>
                            {{-- <td><a href="{{route('Historico.show',  $ingreso->id)}}"><img src="{{$ingreso->photourl}}" width="50%" title="Detalle del Empleado" onmouseover="" onmouseout=""  /></a></td> --}}
                            <td><a href="{{route('Historico.show',  $ingreso->id)}}"><img src="{{asset($ingreso->photourl)}}" width="50%" title="Detalle del Empleado" onmouseover="" onmouseout=""  /></a></td> 
                            
                            <td>
                            {{-- <form action="{{route('Historico.destroy',$ingreso->id)}}" method="POST">    <a href="{{ route('Historico.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                            @method('DELETE')
                                            @csrf 
                              <a href="{{ route('Historico.edit', $ingreso) }}" title="Editar" class="jsgrid-button jsgrid-edit-button">
                                   <i class="far fa-edit"></i>
                                 </a>
                                 <button title="Eliminar" class="jsgrid-button jsgrid-delete-button unstyled-button">
                                   <i class="far fa-trash-alt" type="submit"></i>
                                 </button>
                              </form> --}}
                            </td>
                        </tr>
                        @endforeach
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
 @endsection
@section('scripts')
	<script src="{{asset ('assets/js/data-table.js')}}"></script>

  
@endsection 

resources/views/historico/show.blade.php
@extends('layouts.templates')
@section('title', 'Actuliza Hora de Ingreso')
@section('content')
                                   
	<div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
            Actuliza Hora de Ingreso de Empleado
            <img src="{{asset($ingreso->photourl)}}" width="30%" title="foto" />
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Incio</a></li>
                <li class="breadcrumb-item"><a href="{{ route('Historico.store') }}">Historico</a></li>
                <li class="breadcrumb-item active" aria-current="page">Consulta</li>
              </ol>
            </nav>
          </div>
          <div class="card">
            <div class="card-body">
              {{-- <h4 class="card-title">Categorías</h4> --}}

              <div class="row">
                  <div class="col-12">
                  @if($errors->any())

                  @endif
                  @if (session()->has('actualizada'))
                        					<div class="alert alert-success" role="alert">Fecha/Hora Actualizada Correctamente'</div>
                        					{{session('actualizada')}}
                    					@endif   
                  
                  <form action="/Historico/{{$ingreso->id}}" method="POST">    
                    @csrf
                    @method('PATCH')
	                     <div class="form-group">
			                  <label for="name"><strong>ID del Ingreso</strong></label>
			                  <input type="text" value="{{$ingreso->id}}" name="id" id="id" class="form-control" disabled>
			                </div>


			                <div class="form-group">
                      @if ($errors->has('hora'))
                        <span class="alert alert-danger">
                          <span>{{$errors->first('hora')}}</span>
                        </span>
	                    @endif

                      
                      <div class="form-group">
			                  <label for="hora"><strong>Hora</strong></label>
			                  <input type="text" name="hora" value="{{$ingreso->timestamp}}" id="hora" class="form-control" max="00:00:00" min="23:59:59" >
			                </div> 
	                    
                      <div class="form-group mr-2">
                       <a href="/Historico" class="btn btn-light">Regresar</a>
                       <button type="submit" class="btn btn-primary">Actualizar</button>
      							
      							   </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection
<script src="/images/valida.js" async></script>